export const preguntas = [
    "Ante una señal de Ceda el Paso el Conductor deberá...",
    "El permiso de conducir es una autorización que otorga la autoridad departamental y puede ser retirada con causa justificada",
    "Todo vehículo automotor y los acoplados remolcados por el mismo que circulen por las vías de tránsito, deberán ser objeto de un contrato de seguro de responsabilidad civil por daños a terceros con la cobertura que determina la ley",
    "¿Para qué sirve la luz de posición?",
    "En caso de siniestro de tránsito, usted debe:",
    "Principio de cooperación en el tránsito es: Comportarse conforme a las reglas y actuar en la vía armónicamente, de manera de coordinar las acciones propias con la de los otros usuarios para no provocar conflictos, perturbaciones, ni siniestros, y en definitiva, compartir la vía pública en forma pacífica y ordenada",
    "Existiendo acera transitable: ¿Los peatones pueden ir caminando por la calzada?",
    "Señala  cuál de estos elementos de seguridad pasiva y reduce los daños que se pueden producir cuando ocurre un siniestro:",
    "Los sistemas de seguridad podemos dividirlos en dos grandes grupos: seguirdad activa y seguridad pasiva. ¿Cuál de los siguientes sistemas mencionado actúan antes de una colisión?",
    "El uso del celular mientras conduces reduce nuestra capacidad de atención",
    "¿Cuál es la función del apoya cabezas?",
    "El conductor del vehículo, en una calzada de doble sentido de de circulación, no podrá adelantar a otro vehículo cuando:",
    "Si usted conduce un vehículo y observa a un Agente de Tránsito de perfil:",
    "Con niebla, se deben apagar las luces cortas porque afectan la visibilidad a mediana distancia. Ud. considera esta afirmación como:",
    "Los automotores deberán contar con un par de luces delantera de posición de color amarillas o blancas, y en su parte trasera con un par de color rojo. Las motocicletas están obligadas a llevar una luz de posición roja en su parte trasera",
    "¿Se puede circular con escape sin silenciador?",
    "Circula conduciendo detras de un vehículo el cual a indicado la intención de detenerse, Ud. desea adelantarlo, ¿le está permitido hacerlo por el carril derecho si está libre?",
    "¿Debe tener seguro obligatorio un ciclomotor?",
    "El hidroplaneamiento o Aquaplanning es un fenómeno que se produce cuando:",
    "Al circular con nuestro vehículo lo haremos por el carril:",
    "¿Es recomendable para el peatón llevar chaleco reflectante si circula de noche?",
    "Si quien conduce lo hace a 40Km/h y necesita una frenada de emergencia, la distancia total de la detención se realizará una vez recorridos 20 metros. Si circula a 80Km/h, la distancia total de detención será:",
    "El estrés hace que el conductor...",
    "La baja presión en los neumáticos provoca una flexión externa de estos, lo cual genera calor, con el riesgo que estalle. También causa un desgaste desparejo de la banda de rodamiento",
    "¿Debe estar matriculado un ciclomotor?",// HASTA ACA ESTA TODO OK
    "La principal causa de siniestros viales es debido al...",
    "La siguiente afirmación:La mezcla de medicamentos con alcohol siempre es peligrosa y debe ser evitada, es: ",
    "La persona que ha tomado alcohol...",
    "Que acción debe tomar Ud al momento que percibe que va ha hacer adelantado...",
    "Los vehículos deberán llevar elementos de seguridad como matafuego, balizazs, y dispositivos reflectantes independientes para casos de emergencia.",
    "De día, en condiciones meteorológicas adversas, ¿que luces deberemos de llevar puestas?",
    "¿Puede provocar fatiga conducir con lluvia o en situaciones climatológicas adversas?",
    "Circula conduciendo detrás de un vehículo el cual ha indicado intención de girar a la izquierda Ud. Desea adelantarlo: ¿le está permitido hacerlo por el carril que está libre?",
    "La conducción de un vehículo en forma segura puede verse afectada por diferentes afecciones:",
    "¿Qué deberá hacer un conductor al iniciar un giro a la izquierda desde una calle de doble mano?",
    "Antes de empezar a pasar al vehículo que va delante de usted deberá:",
    "Se puede adelantar a un vehículo que está doblando a la derecha",
    "Adelantamiento correcto es una maniobra realizada:",
    "Un conductor al enfrentar una señal de ceda el paso deberá:",
    "Un cruce regulado:",
    "Un disgusto (altercados, discusiones, depresión, etc.) afecta:",
    "Si su vehículo comienza a patinar al momento de frenar",
    "Con el coche cargado:",
    "En un repecho se puede adelantar a otro vehículo",
    "En cruces donde los semáforos se encuentren apagados o descompuestos, la preferencia será de:",
    "Los vehículos que tienen sus neumáticos con bandas de rodamiento gastadas (menos de 2 mm de profundidad)",
    "Aun tomando descansos, no se deberá conducir por más de 9 horas contínuas",
    "Para enfrentarse a futuras emergencias un conductor prudente debe tener en su vehículo:",
    "¿Cuál es la distancia mínima de seguridad que usted debe mantener con respecto al vehículo que circula delante?",
    "Si usted debe estacionar en bajada",
    "Por norma general, ¿usted deberá circular por la izquierda de la calzada?",
    "Cuando llueve",
    "Por norma general usted deberá circular por el eje de calzada, salvo que transiten otros vehículos",
    "Cuando usted dobla a la derecha:",
    "La velocidad inadecuada y el consumo de alcohol...",
    "Todo vehículo automotor, para transitar por la vía pública deberá poseer obligatoriamente un extintor",
    "¿Puede eventualmente detenerse un automóvil en la banquina de una ruta?",
    "Por definición de vía se entiende:",
    "¿Una mujer embarazada está exenta de colocarse el cinturón de seguridad?",
    "Si la línea a la izquierda es amarilla continua, en el eje de la calzada, significa que:",
    "Todo vehículo empadronado deberá llevar en su parte trasera, una luz blanca que ilumine la matrícula",
    "En caso de querer conducir una persona discapacitada deberá",
    "El apoyacabezas debe quedar a la altura de...",
    "Puede usted, ¿estacionar su vehículo en doble fila?",
    "Los vehículos que no cumplan con las leyes y no ofrezcan la debida seguridad de tránsito, podrán ser retirados de la circulación por la autoridad competente",
    "Si usted viaja como pasajero en una moto, ¿debe llevar el casco abrochado?",
    "¿Se pueden efectuar competiciones en la vía pública, sin autorización de la autoridad competente?",
    "¿Hay medicamentos que pueden afectar el tiempo de reacción?",
    "El alcohol al momento de conducir un vehículo:",
    "Cuando los neumáticos poseen menor presión de aire que la sugerida, las consecuencias son:",
    "Analice esta afirmación: Al aproximarse a un cruce de caminos, una bifurcación, un empalme de carreteras o paso a nivel el conductor deberá tomar precauciones especiales a fin de evitar  siniestro",
    "Todo vehículo automotor y los acoplados remolcados por el mismo que circulen por las vías de tránsito, deberán ser objeto de un contrato de seguro mínimo de responsabilidad civil por daños a terceros",
    "Para disminuir considerablemente la velocidad, salvo el caso de frenado brusco por peligro inminente, y siempre que sea necesario, se colocará el brazo y mano extendidos fuera del vehículo y hacia abajo",
    "Un conductor al enfrentarse a una señal de PARE debe:",
    "La preferencia de paso del vehículo de la derecha no regirá:",
    "¿Cuál es la edad mínima para poder viajar en el asiento delantero del vehículo?",
    " Cuando va detrás de un vehículo durante la noche deben usarse las luces cortas",
    "Las luces altas ¿deben sustituirse por las de alcance medio cuando hay riesgo de encandilamiento?",
    "Ante la proximidad de un vehículo de emergencia usted:",
    "¿Se puede adelantar a un vehículo que está dando paso a peatones?",
    "Cruce peatonal es:",
    "El peatón: ¿tiene preferencia de cruce en cualquier lugar de la calzada?",
    "Los peatones que circulan por la vereda tienen preferencia de paso ante un vehículo que la atraviesa para entrar o salir de un garaje",
    "Al reventarse una neumático se debe:",
    "Ante irregularidades en la documentación o estado del vehículo este puede ser detenido por funcionario de tránsito igual que la documentación (del conductor y del vehículo) previa entrega del recibo pertinente",
    "Los funcionarios del cuerpo de inspectores de tránsito, están facultados para modificar las preferencias establecidas cuando las circunstancias lo requieran:",
    "Usted puede circular sin espejo retrovisor cuando circule a baja velocidad",
    "La distancia prudencial entre dos vehículos que circulan en la misma dirección en carretera es aquella que permite ver al conductor las ruedas traseras del vehículo que va adelante",
    "Las luces cortas o bajas, ¿pueden encandilar a quienes circulan de frente en algún caso?",
    "Según la tabla de valores de alcoholemia o similares en términos de espirometría, el valor 0.8 g/l de alcohol en sangre indica que la motricidad no se verá afectada",
    "En pavimento mojado nunca se debe circular el vehículo en punto muerto",
    "En las calles de doble sentido, los vehículos que circulen en sentido opuesto al cruzarse deberán:",
    "Durante la noche en áreas urbanas los vehículos deben circular con todas las luces reglamentarias encendidas",
    "El uso del cinturón de seguridad es obligatorio para: ",
    "Derecho preferente de paso es:",
    "Usted puede usar la bocina de su vehículo para:",
    "En carretera se debe aminorar la marcha en:",
    "La mayor parte de los accidentes de tránsito por desperfectos del vehículo, a excepción de los frenos, son producidos por:",
    "Es necesario duplicar la distancia entre su vehículo y el que lo antecede en:",
    "Son elementos de seguridad pasiva en los vehículos:",
    "En los cruces con semáforo, la preferencia de paso es de los peatones frente a cualquier vehículo que gira",
    "En las esquinas (aunque el cruce no esté pintado) la preferencia de paso:",
    "Usted debe reducir la velocidad a paso de peatón:",
    "Los traumatismos causados por accidentes de tránsito:",
    "En condiciones de tránsito normales, un vehículo podrá ser conducido marcha atrás solo:",
    "¿Cuál es la distancia mínima que debe mantener un conductor con respecto al vehículo que circula delante de usted a 60 km/h?",
    "Un vehículo que circula a 70 km/h necesita para detenerse:",
    "Cuando se trata de evitar un choque de frente en carretera, usted debe:",
    "La velocidad ideal para conducir con seguridad en carretera está entre:",
    "Los objetos sueltos, duros y con puntas depositados en los estantes delanteros y traseros, se pueden convertir en proyectiles peligrosos en una frenada brusca",
    "¿Cuál es la velocidad máxima establecida en zona urbana donde no hay señalización que regule la misma?",
    "¿Cuál es la velocidad máxima permitida para circular en ciudad?",
    "En condiciones de tránsito normales, un vehículo podrá ser conducido marcha atrás solo:",
    "¿Cuál es la distancia mínima que debe mantener un conductor con respecto al vehículo que circula delante de usted a 60 km/h?",
    "Un vehículo que circula a 70 km/h necesita para detenerse:",
    "Cuando se trata de evitar un choque de frente en carretera, usted debe:",
    " Cuando el vehículo sufre un desperfecto en la ruta se debe colocar la baliza o triángulo por lo menos a 50 metros:",
    "Los objetos sueltos, duros y con puntas depositados en los estantes delanteros y traseros, se pueden convertir en proyectiles peligrosos en una frenada brusca",
    " Son elementos de seguridad activa en los vehículos:",
    "Que tramo de la calle se debe utilizar exclusivamente para manejar un vehículo?",
    "Para conducir adecuadamente es importante observar la luz del semáforo que esta de frente a Ud.",
    "Ante destellantes amarillos instalados en las cercanías de las escuelas: a que velocidad debe circular",
    "El ruido que produce el silenciador en mal estado no aumenta la fatiga del conductor",
    "El conductor de un vehículo puede sobrepasar a otro por la derecha cuando",
    "Cuando se maneja por períodos de más de cuatro horas se deberá descansar por lo menos:",
    "En los días de lluvia se debe disminuir la velocidad aunque las condiciones del vehículo sean óptimas",
    "Cuando los neumáticos tienen poca presión de aire, se ahora combustible:",
    "Los inspectores de la IMM y/o policía de tránsito están facultados al retiro de la documentación del conductor y/o vehículo",
    "Del uso del casco:",
    "En un cruce regulado por semáforos:",
    "Sobre el cinturón de seguridad:",
    "Sobre el carril preferencial de Bus:",
    "Los peatones adultos mayores pueden presentar desventajas en el tránsito tales como:",
    "Los efectos del alcohol dependen de factores como:",
    "¿Qué luces debe llevar encendidas un vehículo en forma permanente según la ley 18.191?",
    "Omitir información en las evaluaciones médicas de la IM:",
    "Tienen preferencia de paso cuando hagan las señales correspondientes",
    "Si se produce el hidroplaneamiento, usted debe",
    "Queda prohibido el uso de luces rojas visibles por el frente del vehículo y luces blancas visibles por atrás (excepto las que iluminan la placa de identificación, o las que indican marcha atrás)",
    "Conduce su vehículo por una ruta nacional, ¿Cuál es la velocidad máxima que le está permitido circular si no existen carteles que especifiquen con precisión una velocidad?",
    "Si circula de noche por una vía insuficientemente iluminada a más de 40 kilómetros por hora, ¿está obligado a llevar encendida la luz de bajo alcance o luces cortas en su vehículo?",
    "Los agentes de tránsito podrán retener el permiso de conducir entregando el recibo correspondiente",
    "Si estoy conduciendo un vehículo en el tránsito y me irrito o me enojo por determinado motivo mi comportamiento debe ser",
    "Esta terminantemente prohibido estacionar",
    "Circulando en el mismo sentido de un vehículo de emergencia ud. debe aumentar la distancia que lo separa del mismo",
    "La velocidad máxima a la que se puede conducir en carretera, salvo expresas excepciones es",
    "En caso de quedarse sin frenos debe dejar que el vehículo aminore la velocidad evitando los obstáculos",
    "Que debe hacer un conductor al indicar el giro a la derecha?",
    "Nunca debe adelantarse a un vehículo que esta dando paso a peatones",
    "Por norma general Ud debe circular por la mitad derecha de la calzada",
    "Ante la proximidad de vehículos de emergencia, despejar rápidamente la calzada permaneciendo donde no moleste",
    "Cuando un automóvil al salir del garage cruza la vereda, obtiene la preferencia sobre los peatones que circulan en ella",
    "Debe prestar atención de no encandilar a los que vienen en sentido contrario usando las luces cortas",
    "La velocidad máxima a la que se debe conducir en la zona urbana, salvo expresas excepciones, es:",
    "Al encontrarse la calle mojada por la lluvia ¿Que debe hacer usted?",
    "De las siguientes medidas, ¿cuál de ellas cree Ud. que es conveniente aplicar, como norma general, a los heridos en un siniestro donde participan motociclistas?",
    "¿Cómo calcula Ud. la distancia de seguridad que debe guardar entre su vehículo y el vehiculo que va delante circulando en ruta?",
    "Circulando con su vehículo en un día de niebla, ¿qué precaución, entre otras, debe tomar?",
    "En vías urbanas de doble sentido de circulación, ¿en qué lado de la calzada podrá estacionar su vehículo, si no está prohibido?",
    "En la ciudad, ¿le está permitido a Ud. adelantar con su vehículo por la derecha a otro vehículo si para ello tiene que invadir un carril reservado para autobuses?",
    "Principio de seguridad vial: los usuarios de las vías de tránsito deben abstenerse de todo acto que pueda constituir un peligro o un obstáculo para la circulación, poner en peligro a personas o, causar daños a bienes públicos o privados.",
    "¿Usar casco de motocicleta, reduce el riesgo de sufrir una lesión severa en un 10%?",
    "Una motocicleta puede circular con 2 ocupante",
    "Las causas de accidentes provocadas por distracciones pueden ser por",
    "Si usted va a realizar un giro a la izquierda, circulando previamente por una calle de una sola mano, debe:",
    "Cuando el vehículo posee sistema antibloqueo de frenos (ABS), ante una frenada de emergencia se debe:",
    "Se considera exceso de velocidad",
    "Carril preferencial es:",
    "La luz amarilla o ámbar:",
    "En caso de un siniestro con heridos, usted debe:",
    "Se puede estacionar en un cruce peatonal o a menos de 5 metros de él",
    "¿Qué indica la seña manual de brazo y mano extendidos hacia abajo?",
    "El uso del Airbag es eficaz si además se utiliza el cinturón de seguridad",
    "Con mucha carga en la valija del automóvil se afectara:",
    "¿Dónde puede Ud. realizar un cambio de frente en la misma calzada por la que circula?",
    "A llegar a un cruce con su vehículo Ud. tiene luz verde al frente y una ambulancia haciendo uso de la sirena y luces intermitentes, aparece por la izquierda pidiendo paso, intentando cruzar con luz roja al frente, que debe hacer Ud.?",
    "Para reducir los efectos del alcohol en la sangre, al momento de asumir la conducción de cualquier vehículo debemos:",
    "Cuando Usted cambia de dirección y gira a la derecha, ud. debe:",
    "¿Qué factores pueden incidir en la generación de aquaplanning o hidroplaneamiento?",
    "Circula por una vía con dos carriles para cada sentido de circulación conduciendo su vehículo por un tramo de vía en la que no está prohibido adelantar, ¿qué distancia de seguridad debe dejar entre su vehículo y el vehículo que circula delante de Ud.?",
    "Si, dentro de ciudad, circula conduciendo su vehículo a 70 kilómetros por hora y no existen carteles señalizadores de velocidad, estando la vía despejada y sin conflictos, Ud. ¿debe modificar la velocidad?",
    "¿Es correcto circular por la banquina?",
    "Cuando los peatones caminan en las rutas tienen que transitar:",
    "Cuando Ud. se acerca a un paso a nivel y la barrera comienza a bajar, ¿debe Ud. cruzar el paso a nivel?",
    " Cuando llueve, la calzada esta mojada y el vehículo...",
    "¿Qué indica una luz roja intermitente?",
    "Ud. circula conduciendo su vehículo por una vía urbana. ¿Debe llevar abrochado el cinturón de seguridad?",
    "Como debe realizar la maniobra de estacionamiento:",
    ];
