export const preguntas = [
    "Ante una señal de Ceda el Paso el Conductor deberá...",
    "El permiso de conducir es una autorización que otorga la autoridad departamental y puede ser retirada con causa justificada",
    "Todo vehículo automotor y los acoplados remolcados por el mismo que circulen por las vías de tránsito, deberán ser objeto de un contrato de seguro de responsabilidad civil por daños a terceros con la cobertura que determina la ley",
    "¿Para qué sirve la luz de posición?",
    "En caso de siniestro de tránsito, usted debe:",
    "Principio de cooperación en el tránsito es: Comportarse conforme a las reglas y actuar en la vía armónicamente, de manera de coordinar las acciones propias con la de los otros usuarios para no provocar conflictos, perturbaciones, ni siniestros, y en definitiva, compartir la vía pública en forma pacífica y ordenada",
    "Existiendo acera transitable: ¿Los peatones pueden ir caminando por la calzada?",
    "Señala  cuál de estos elementos de seguridad pasiva y reduce los daños que se pueden producir cuando ocurre un siniestro:",
    "Los sistemas de seguridad podemos dividirlos en dos grandes grupos: seguirdad activa y seguridad pasiva. ¿Cuál de los siguientes sistemas mencionado actúan antes de una colisión?",
    "El uso del celular mientras conduces reduce nuestra capacidad de atención",
    "¿Cuál es la función del apoya cabezas?",
    "El conductor del vehículo, en una calzada de doble sentido de de circulación, no podrá adelantar a otro vehículo cuando:",
    "Si usted conduce un vehículo y observa a un Agente de Tránsito de perfil:",
    "Con niebla, se deben apagar las luces cortas porque afectan la visibilidad a mediana distancia. Ud. considera esta afirmación como:",
    "Los automotores deberán contar con un par de luces delantera de posición de color amarillas o blancas, y en su parte trasera con un par de color rojo. Las motocicletas están obligadas a llevar una luz de posición roja en su parte trasera",
    "¿Se puede circular con escape sin silenciador?",
    "Circula conduciendo detras de un vehículo el cual a indicado la intención de detenerse, Ud. desea adelantarlo, ¿le está permitido hacerlo por el carril derecho si está libre?",
    "¿Debe tener seguro obligatorio un ciclomotor?",
    "El hidroplaneamiento o Aquaplanning es un fenómeno que se produce cuando:",
    "Al circular con nuestro vehículo lo haremos por el carril:",
    "¿Es recomendable para el peatón llevar chaleco reflectante si circula de noche?",
    "Si quien conduce lo hace a 40Km/h y necesita una frenada de emergencia, la distancia total de la detención se realizará una vez recorridos 20 metros. Si circula a 80Km/h, la distancia total de detención será:",
    "El estrés hace que el conductor...",
    "La baja presión en los neumáticos provoca una flexión externa de estos, lo cual genera calor, con el riesgo que estalle. También causa un desgaste desparejo de la banda de rodamiento",
    "¿Debe estar matriculado un ciclomotor?",// HASTA ACA ESTA TODO OK
    "La principal causa de siniestros viales es debido al...",
    "La siguiente afirmación:La mezcla de medicamentos con alcohol siempre es peligrosa y debe ser evitada, es: ",
    "La persona que ha tomado alcohol...",
    "Que acción debe tomar Ud al momento que percibe que va ha hacer adelantado...",
    "Los vehículos deberán llevar elementos de seguridad como matafuego, balizazs, y dispositivos reflectantes independientes para casos de emergencia.",
    "De día, en condiciones meteorológicas adversas, ¿que luces deberemos de llevar puestas?",
    "¿Puede provocar fatiga conducir con lluvia o en situaciones climatológicas adversas?",
    "Circula conduciendo detrás de un vehículo el cual ha indicado intención de girar a la izquierda Ud. Desea adelantarlo: ¿le está permitido hacerlo por el carril que está libre?",
    "La conducción de un vehículo en forma segura puede verse afectada por diferentes afecciones:",
    "¿Qué deberá hacer un conductor al iniciar un giro a la izquierda desde una calle de doble mano?",
    "Antes de empezar a pasar al vehículo que va delante de usted deberá:",
    "Se puede adelantar a un vehículo que está doblando a la derecha",
    "Adelantamiento correcto es una maniobra realizada:",
    "Un conductor al enfrentar una señal de ceda el paso deberá:",
    "Un cruce regulado:",
    "Un disgusto (altercados, discusiones, depresión, etc.) afecta:",
    "Si su vehículo comienza a patinar al momento de frenar",
    "Con el coche cargado:",
    "En un repecho se puede adelantar a otro vehículo",
    "En cruces donde los semáforos se encuentren apagados o descompuestos, la preferencia será de:",
    "Los vehículos que tienen sus neumáticos con bandas de rodamiento gastadas (menos de 2 mm de profundidad)",
    "Aun tomando descansos, no se deberá conducir por más de 9 horas contínuas",
    "Para enfrentarse a futuras emergencias un conductor prudente debe tener en su vehículo:",
    "¿Cuál es la distancia mínima de seguridad que usted debe mantener con respecto al vehículo que circula delante?",
    "Si usted debe estacionar en bajada",
    "Por norma general, ¿usted deberá circular por la izquierda de la calzada?",
    "Cuando llueve",
    "Por norma general usted deberá circular por el eje de calzada, salvo que transiten otros vehículos",
    "Cuando usted dobla a la derecha:",
    "La velocidad inadecuada y el consumo de alcohol...",
    "Todo vehículo automotor, para transitar por la vía pública deberá poseer obligatoriamente un extintor",
    "¿Puede eventualmente detenerse un automóvil en la banquina de una ruta?",
    "Por definición de vía se entiende:",
    "¿Una mujer embarazada está exenta de colocarse el cinturón de seguridad?",
    "Si la línea a la izquierda es amarilla continua, en el eje de la calzada, significa que:",
    "Todo vehículo empadronado deberá llevar en su parte trasera, una luz blanca que ilumine la matrícula",
    "En caso de querer conducir una persona discapacitada deberá",
    "El apoyacabezas debe quedar a la altura de...",
    "Puede usted, ¿estacionar su vehículo en doble fila?",
    "Los vehículos que no cumplan con las leyes y no ofrezcan la debida seguridad de tránsito, podrán ser retirados de la circulación por la autoridad competente",
    "Si usted viaja como pasajero en una moto, ¿debe llevar el casco abrochado?",
    "¿Se pueden efectuar competiciones en la vía pública, sin autorización de la autoridad competente?",
    "¿Hay medicamentos que pueden afectar el tiempo de reacción?",
    "El alcohol al momento de conducir un vehículo:",
    "Cuando los neumáticos poseen menor presión de aire que la sugerida, las consecuencias son:",
    "Analice esta afirmación: Al aproximarse a un cruce de caminos, una bifurcación, un empalme de carreteras o paso a nivel el conductor deberá tomar precauciones especiales a fin de evitar  siniestro",
    "Todo vehículo automotor y los acoplados remolcados por el mismo que circulen por las vías de tránsito, deberán ser objeto de un contrato de seguro mínimo de responsabilidad civil por daños a terceros",
    "Para disminuir considerablemente la velocidad, salvo el caso de frenado brusco por peligro inminente, y siempre que sea necesario, se colocará el brazo y mano extendidos fuera del vehículo y hacia abajo",
    "Un conductor al enfrentarse a una señal de PARE debe:",
    "La preferencia de paso del vehículo de la derecha no regirá:",
    "¿Cuál es la edad mínima para poder viajar en el asiento delantero del vehículo?",
    " Cuando va detrás de un vehículo durante la noche deben usarse las luces cortas",
    "Las luces altas ¿deben sustituirse por las de alcance medio cuando hay riesgo de encandilamiento?",
    "Ante la proximidad de un vehículo de emergencia usted:",
    "¿Se puede adelantar a un vehículo que está dando paso a peatones?",
    "Cruce peatonal es:",
    "El peatón: ¿tiene preferencia de cruce en cualquier lugar de la calzada?",
    "Los peatones que circulan por la vereda tienen preferencia de paso ante un vehículo que la atraviesa para entrar o salir de un garaje",
    "Al reventarse una neumático se debe:",
    "Ante irregularidades en la documentación o estado del vehículo este puede ser detenido por funcionario de tránsito igual que la documentación (del conductor y del vehículo) previa entrega del recibo pertinente",
    "Los funcionarios del cuerpo de inspectores de tránsito, están facultados para modificar las preferencias establecidas cuando las circunstancias lo requieran:",
    "Usted puede circular sin espejo retrovisor cuando circule a baja velocidad",
    "La distancia prudencial entre dos vehículos que circulan en la misma dirección en carretera es aquella que permite ver al conductor las ruedas traseras del vehículo que va adelante",
    "Las luces cortas o bajas, ¿pueden encandilar a quienes circulan de frente en algún caso?",
    "Según la tabla de valores de alcoholemia o similares en términos de espirometría, el valor 0.8 g/l de alcohol en sangre indica que la motricidad no se verá afectada",
    "En pavimento mojado nunca se debe circular el vehículo en punto muerto",
    "En las calles de doble sentido, los vehículos que circulen en sentido opuesto al cruzarse deberán:",
    "Durante la noche en áreas urbanas los vehículos deben circular con todas las luces reglamentarias encendidas",
    "El uso del cinturón de seguridad es obligatorio para: ",
    "Derecho preferente de paso es:",
    "Usted puede usar la bocina de su vehículo para:",
    "En carretera se debe aminorar la marcha en:",
    "La mayor parte de los accidentes de tránsito por desperfectos del vehículo, a excepción de los frenos, son producidos por:",
    "Es necesario duplicar la distancia entre su vehículo y el que lo antecede en:",
    "Son elementos de seguridad pasiva en los vehículos:",
    "En los cruces con semáforo, la preferencia de paso es de los peatones frente a cualquier vehículo que gira",
    "En las esquinas (aunque el cruce no esté pintado) la preferencia de paso:",
    "Usted debe reducir la velocidad a paso de peatón:",
    "Los traumatismos causados por accidentes de tránsito:",
    "En condiciones de tránsito normales, un vehículo podrá ser conducido marcha atrás solo:",
    "¿Cuál es la distancia mínima que debe mantener un conductor con respecto al vehículo que circula delante de usted a 60 km/h?",
    "Un vehículo que circula a 70 km/h necesita para detenerse:",
    "Cuando se trata de evitar un choque de frente en carretera, usted debe:",
    "La velocidad ideal para conducir con seguridad en carretera está entre:",
    "Los objetos sueltos, duros y con puntas depositados en los estantes delanteros y traseros, se pueden convertir en proyectiles peligrosos en una frenada brusca",
    "¿Cuál es la velocidad máxima establecida en zona urbana donde no hay señalización que regule la misma?",
    "¿Cuál es la velocidad máxima permitida para circular en ciudad?",
    "En condiciones de tránsito normales, un vehículo podrá ser conducido marcha atrás solo:",
    "¿Cuál es la distancia mínima que debe mantener un conductor con respecto al vehículo que circula delante de usted a 60 km/h?",
    "Un vehículo que circula a 70 km/h necesita para detenerse:",
    "Cuando se trata de evitar un choque de frente en carretera, usted debe:",
    " Cuando el vehículo sufre un desperfecto en la ruta se debe colocar la baliza o triángulo por lo menos a 50 metros:",
    "Los objetos sueltos, duros y con puntas depositados en los estantes delanteros y traseros, se pueden convertir en proyectiles peligrosos en una frenada brusca",
    " Son elementos de seguridad activa en los vehículos:",
    "Que tramo de la calle se debe utilizar exclusivamente para manejar un vehículo?",
    "Para conducir adecuadamente es importante observar la luz del semáforo que esta de frente a Ud.",
    "Ante destellantes amarillos instalados en las cercanías de las escuelas: a que velocidad debe circular",
    "El ruido que produce el silenciador en mal estado no aumenta la fatiga del conductor",
    "El conductor de un vehículo puede sobrepasar a otro por la derecha cuando",
    "Cuando se maneja por períodos de más de cuatro horas se deberá descansar por lo menos:",
    "En los días de lluvia se debe disminuir la velocidad aunque las condiciones del vehículo sean óptimas",
    "Cuando los neumáticos tienen poca presión de aire, se ahora combustible:",
    "Los inspectores de la IMM y/o policía de tránsito están facultados al retiro de la documentación del conductor y/o vehículo",
    "Del uso del casco:",
    "En un cruce regulado por semáforos:",
    "Sobre el cinturón de seguridad:",
    "Sobre el carril preferencial de Bus:",
    "Los peatones adultos mayores pueden presentar desventajas en el tránsito tales como:",
    "Los efectos del alcohol dependen de factores como:",
    "¿Qué luces debe llevar encendidas un vehículo en forma permanente según la ley 18.191?",
    "Omitir información en las evaluaciones médicas de la IM:",
    "Tienen preferencia de paso cuando hagan las señales correspondientes",
    "Si se produce el hidroplaneamiento, usted debe",
    "Queda prohibido el uso de luces rojas visibles por el frente del vehículo y luces blancas visibles por atrás (excepto las que iluminan la placa de identificación, o las que indican marcha atrás)",
    "Conduce su vehículo por una ruta nacional, ¿Cuál es la velocidad máxima que le está permitido circular si no existen carteles que especifiquen con precisión una velocidad?",
    "Si circula de noche por una vía insuficientemente iluminada a más de 40 kilómetros por hora, ¿está obligado a llevar encendida la luz de bajo alcance o luces cortas en su vehículo?",
    "Los agentes de tránsito podrán retener el permiso de conducir entregando el recibo correspondiente",
    "Si estoy conduciendo un vehículo en el tránsito y me irrito o me enojo por determinado motivo mi comportamiento debe ser",
    "Esta terminantemente prohibido estacionar",
    "Circulando en el mismo sentido de un vehículo de emergencia ud. debe aumentar la distancia que lo separa del mismo",
    "La velocidad máxima a la que se puede conducir en carretera, salvo expresas excepciones es",
    "En caso de quedarse sin frenos debe dejar que el vehículo aminore la velocidad evitando los obstáculos",
    "Que debe hacer un conductor al indicar el giro a la derecha?",
    "Nunca debe adelantarse a un vehículo que esta dando paso a peatones",
    "Por norma general Ud debe circular por la mitad derecha de la calzada",
    "Ante la proximidad de vehículos de emergencia, despejar rápidamente la calzada permaneciendo donde no moleste",
    "Cuando un automóvil al salir del garage cruza la vereda, obtiene la preferencia sobre los peatones que circulan en ella",
    "Debe prestar atención de no encandilar a los que vienen en sentido contrario usando las luces cortas",
    "La velocidad máxima a la que se debe conducir en la zona urbana, salvo expresas excepciones, es:",
    "Al encontrarse la calle mojada por la lluvia ¿Que debe hacer usted?",
    "De las siguientes medidas, ¿cuál de ellas cree Ud. que es conveniente aplicar, como norma general, a los heridos en un siniestro donde participan motociclistas?",
    "¿Cómo calcula Ud. la distancia de seguridad que debe guardar entre su vehículo y el vehiculo que va delante circulando en ruta?",
    "Circulando con su vehículo en un día de niebla, ¿qué precaución, entre otras, debe tomar?",
    "En vías urbanas de doble sentido de circulación, ¿en qué lado de la calzada podrá estacionar su vehículo, si no está prohibido?",
    "En la ciudad, ¿le está permitido a Ud. adelantar con su vehículo por la derecha a otro vehículo si para ello tiene que invadir un carril reservado para autobuses?",
    "Principio de seguridad vial: los usuarios de las vías de tránsito deben abstenerse de todo acto que pueda constituir un peligro o un obstáculo para la circulación, poner en peligro a personas o, causar daños a bienes públicos o privados.",
    "¿Usar casco de motocicleta, reduce el riesgo de sufrir una lesión severa en un 10%?",
    "Una motocicleta puede circular con 2 ocupante",
    "Las causas de accidentes provocadas por distracciones pueden ser por",
    "Si usted va a realizar un giro a la izquierda, circulando previamente por una calle de una sola mano, debe:",
    "Cuando el vehículo posee sistema antibloqueo de frenos (ABS), ante una frenada de emergencia se debe:",
    "Se considera exceso de velocidad",
    "Carril preferencial es:",
    "La luz amarilla o ámbar:",
    "En caso de un siniestro con heridos, usted debe:",
    "Se puede estacionar en un cruce peatonal o a menos de 5 metros de él",
    "¿Qué indica la seña manual de brazo y mano extendidos hacia abajo?",
    "El uso del Airbag es eficaz si además se utiliza el cinturón de seguridad",
    "Con mucha carga en la valija del automóvil se afectara:",
    "¿Dónde puede Ud. realizar un cambio de frente en la misma calzada por la que circula?",
    "A llegar a un cruce con su vehículo Ud. tiene luz verde al frente y una ambulancia haciendo uso de la sirena y luces intermitentes, aparece por la izquierda pidiendo paso, intentando cruzar con luz roja al frente, que debe hacer Ud.?",
    "Para reducir los efectos del alcohol en la sangre, al momento de asumir la conducción de cualquier vehículo debemos:",
    "Cuando Usted cambia de dirección y gira a la derecha, ud. debe:",
    "¿Qué factores pueden incidir en la generación de aquaplanning o hidroplaneamiento?",
    "Circula por una vía con dos carriles para cada sentido de circulación conduciendo su vehículo por un tramo de vía en la que no está prohibido adelantar, ¿qué distancia de seguridad debe dejar entre su vehículo y el vehículo que circula delante de Ud.?",
    "Si, dentro de ciudad, circula conduciendo su vehículo a 70 kilómetros por hora y no existen carteles señalizadores de velocidad, estando la vía despejada y sin conflictos, Ud. ¿debe modificar la velocidad?",
    "¿Es correcto circular por la banquina?",
    "Cuando los peatones caminan en las rutas tienen que transitar:",
    "Cuando Ud. se acerca a un paso a nivel y la barrera comienza a bajar, ¿debe Ud. cruzar el paso a nivel?",
    " Cuando llueve, la calzada esta mojada y el vehículo...",
    "¿Qué indica una luz roja intermitente?",
    "Ud. circula conduciendo su vehículo por una vía urbana. ¿Debe llevar abrochado el cinturón de seguridad?",
    "Como debe realizar la maniobra de estacionamiento:",
    ];

export const respuestas = [
    ["Reducir la velocidad, detenerse si es necesario y permitir el paso a los usuarios que se aproximen a la intersección por la otra vía", "Continuar la marcha", "Disminuir la marcha y solo dar preferencia a los vehículos que aparezcan por la derecha", "Detener el vehículo inmediatamente"],
    ["Verdadero", "Falso"],
    ["Verdadero", "Falso"],
    ["Para indicar la presencia, altura y ancho del vehículo", "Solamente, para indicar el ancho total del vehículo", "Para mejorar el alumbrado de la carretera"],
    ["Ninguna es correcta", "Si es motociclista quitar el casco para ver lesiones", "Ayudarlo a incorporarse y que camine para verificar que no tiene daños", "Primero dar de beber al lesionado"],
    ["Verdadero", "Falso"],
    ["En desacuerdo, los peatones deberán circular por las aceras, sin utilizar la calle ni provocar molestias o transtornos a los demás usuarios", "Solo cuando llueve", "Totalmente de acuerdo"],
    ["Cinturones de seguridad", "Luces", "Neumáticos"],
    ["Neumáticos", "Cinturón", "Sistema de retención infantil", "Casco"],
    ["Verdadero", "Falso"],
    ["Evitar lesiones cervicales", "Evitar lesiones de cabeza", "Evitar fatiga"],
    ["Todas son correctas", "Se apoximen a un paso a nivel o lo atraviesen", "Acceda a una intersección", "La señalización así lo determine"],
    ["Puede continuar la marcha", "Debe doblar a la izquieda o a la derecha", "Debe detener la marcha", "Debe detenerse ya que indica detención de todo el tránsito"],
    ["Inválida, ya que las luces cortas deben utilizarse de forma permanente", "Válida, porque deben encenderse las luces largas para una mayor visión", "Válida, porque la mejor luz es la de posición para esa cirunstancia climática"],
    ["Verdadero", "Falso"],
    ["No", "Si"],
    ["Si", "No"],
    ["Si","No"],
    ["Ambas son correctas", "Ninguna es correcta", "Circula a exceso de velocidad y sobre pavimento mojado", "Cuando el dibujo de los neumáticos no puede desalojar el agua de la calzada"],
    ["De la derecha como norma general", "Que más convenga por mi destino", "Mas al centro posible, para permitir la entrada a los que vienen por la derecha"],
    ["Si, aumenta la visibilidad sobre el peatón", "No es necesario"],
    ["Mayor", "Menor", "Igual"],
    ["Sea más hostil con los demás usuarios", "Asuma menos riesgos", "Respete más la señalización"],
    ["Verdadero", "Falso"],
    ["Verdadero", "Falso"],
    ["factor humano.", "factor vehículo.", "factor vía."],
    ["Verdadera", "Falsa"],
    [ "subestima sus efectos, como norma general", "normalmente es consciente de sus efectos", "conduce con mas precaución, como norma general "],
    ["mantener o disminuir la velocidad", "indicar con el indicador de dirección derecho, que permite el adelantamiento", "aumentar la velocidad"],
    ["Estoy de acuerdo con la afirmación", "No estoy de acuerdo. Es necesario llevar nada más que la documentación del vehículo"],
    ["Siempre las de posición y las de corto alcance", "Las largas si la niebla es muy espesa", "Ninguna luz es necesaria durante el día"],
    ["Si.", "No."],
    ["Si.", "No."],
    ["Todas son correctas", "Los transtornos emocionales y psiquiátricos", "Enfermedades neurológicas", "Transtornos de sueño"],
    ["Aproximarse a la línea central del eje de la calzada", "Ubicarse del lado izquierdo del eje de la  calzada", "Acercarse lo más a la derecha posible", "Ninguna es correcta"],
    ["Mirar por el espejo retrovisor y prender el señalero", "Colocarse en la senda derecha y prender el señalero", "Tocar bocina", "Hacer cambio de luces"],
    ["Verdadero", "Falso"],
    ["Por el costado izquierdo del vehículo que desea adelantar", " Por la banquina si la hubiera", "Nunca se debe adelantar", "Por el costado derecho del vehículo que desea adelantar"],
    ["Reducir la velocidad y detenerse su fuera necesario", "Acelerar", "Detenerse siempre", "Seguir su marcha a la misma velocidad"],
    ["Es aquel en el que existe semáforos funcionando regularmente un inspector o un agente de tránsito", "Ninguna es correcta", "En el que existe cualquier tipo de señal"],
    ["El tiempo de reacción", "La visión lateral", "La audición", "Ninguna es correcta"],
    ["Procure detenerlo bombeando intermitentemente el freno", "Frene enérgicamente", "Acelere", "Todas son incorrectas"],
    ["Las distancias de frenado son mayores", "La aceleración será mas fácil", "Necesitará menor distancia para pasar y parar", "Todas son incorrectas"],
    ["Falso", "Verdadero"],
    ["Los vehículos que aparezcan por la derecha","Los vehículos que aparezcan por la izquierda", "Los que llegan primero al cruce", "Los que circulan por la avenida"],
    ["No debe circular", "Deben circular solo de día", "Deben circular a bajas velocidades", "Deben circular solo de noche"],
    ["Verdadero", "Falso"],
    ["Todas son correctas", "Un extintor", "Dos balizas o triángulos", "Juegos para entretener niños si viajan con ellos"],
    ["La mitad en metros de la velocidad en Km/h", "Un cuarto en metros de la velocidad en Km/h", "El doble en metros de la velocidad en Km/h", "Ninguna es correcta"],
    ["Aplica el freno de manos y gira las ruedas hacia el cordón de la vereda","Deja derecho el auto y aplica el freno de mano","Aplica el freno de manos y gira las ruedas en sentido contrario al cordón de la vereda","Ninguna es correcta"],
    ["Falso", "Verdadero"],
    ["Debe circular a la derecha del centro de la calzada", "Debe circular en el centro de la calzada", "Debe circular en el centro de la calzada siempre y cuando no venga otro vehículo de frente", "Debe circular a la izquierda de la calzada"],
    ["Falso", "Verdadero"],
    ["Debe mirar por el espejo retrovisor, encender el señalero y acercarse al cordón derecho", "Debe encender el señalero derecho", "Debe acercar el vehículo a la izquierda, encender el señalero y doblar con precaución"],
    ["Son factores de riesgo en siniestralidad vial", "No son causas de siniestros de tránsito, pero si laborales", "Pocas veces provocan siniestros en general. Depende de cada persona"],
    ["Verdadero", "Falso"],
    ["Si", "No"],
    ["Es la carretera, camino o calle abierta a la circulación pública", "Es la parte donde circulan los vehículos", "Es la parte donde circulan los buses"],
    ["No", "Si"],
    ["Está prohibido adelantar", "Se puede adelantar y/o girar a la izquierda", "Sólo puede adelantar si está en sus curvas"],
    ["Verdadero", "Falso"],
    ["Ambas son correctas", "Solicitar autorización especial", "Tener el vehículo adecuado a su discapacidad"],
    ["Los ojos", "La nariz", "La boca"],
    ["No, en ningún caso", "Sí. Si es solo para una rápida diligencia"],
    ["La afirmación es correcta", "La afirmación es incorrecta"],
    ["Si, y el conductor es responsable de que lo lleve abrochado", "No"],
    ["No, porque está prohibido", "Sí, en un espacio cerrado al tráfico por el vehículo con bandera roja hasta otro con bandera a cuadros", "Sí, siempre que no se molesten  a otros usuarios"],
    ["Si, por eso debe consultar con su médico las especificaciones", "No, no afectan", "Solo si antes hemos ingerido alcohol"],
    ["Aumenta el tiempo de reación", "Aumenta la distancia de frenado", "Disminuye la distancia de detención"],
    ["Se consume mayor cantidad de combustible y existe riesgo de reventón", "Los neumáticos se gastan menos", "Se controla mejor el vehículo", "Se ahorra combustible"],
    ["Es correcto , ya que todo conductor deberá tomar precauciones especiales a fin de evitar cualquier siniestro en las circunstancias descritas", "Es correcto, la afirmación esta basada en la filosofía de agilizar el tránsito"],
    ["La afirmación es correcta totalmente", "La afirmación es incorrecta. Si no tengo dinero no estoy obligado a contratar un seguro de ninguna especie"],
    ["Verdadero", "Falso"],
    ["Detener totalmente la marcha", "Reducir la velocidad y detenerse si fuera necesario", "Reducir un poco la velocidad y continuar","Seguir su marcha a la misma velocidad"],
    ["En los cruces regulados con semáforos o agentes de tránsito", "En los cruces no regulados","En las vias doble tránsito"],
    ["12 años","6 años", "1 año","Ninguna es correcta"],
    ["Cuando la distancia haga innecesarias las luces largas", "En ningún momento", "Cuando la visibilidad sea muy buena", "Ninguna es correcta"],
    ["Si", "No"],
    ["Despeja rápidamente la calzada permaneciendo detenido donde no moleste", "Aumentar la velocidad", "Ninguna es correcta", "Hacer cambio de luces y tocar la bocina para avisar al resto de los conductores"],
    ["No", "Sí, pero reduciendo la velocidad"],
    ["Parte de la calle habilitada para ser atravesada por peatones", "Los llamados lomos de burro", "Las señalizadas con franjas blancas paralelas", "Parte de la vereda donde se debe esperar hasta poder cruzar"],
    ["Falso", "Verdadero"],
    ["Verdadero","Falso"],
    ["Tomar fuertemente el volante y frenar suavemente como sea posible", "Frenar bruscamente", "Quitar el pie del acelerador y girar para el lado que reventó el neumático", "Frenar suavemente arrimando el auto al borde dereho hasta detenerse"],
    ["Verdadero", "Falso"],
    ["Verdadero", "Falso"],
    ["Falso", "Verdadero"],
    ["Falso", "Verdadero"],
    ["Si", "No"],
    ["Verdadero", "Falso"], 
    ["Verdadero", "Falso"],
    ["No pasar el eje de la calzada, demarcado o imaginario", "Encender las luces bajas", "Hacer un destello con las luces y acercarse lo más posible a la derecha", "Circular por el eje de la calzada, demarcado o imaginario"],
    ["Verdadero", "Falso"],
    ["Para todo los ocupantes del vehículo", "Solo para los ocupantes de atrás", "Ninguna es correcta", "Solo para los ocupantes de los asientos delanteros"],
    ["La facultad de un peatón o un conductor de un vehículo para proseguir su marcha", "La facultad del conductor en el vehículo para cambiar de dirección careciendo de preferencia", "La facultad de un vehículo para no detener la marcha al ingresar a una calle preferencial", "Ninguna es correcta"],
    ["Prevenir un accidente en caso de extrema necesidad", "Siempre, salvo cuando pasa frente de un hospital", "Avisar que vas a estacionar", "Apurar al que va adelante"],
    ["Todas son correctas", "Paso de nivel y puentes", "Curvas y cruces", "Zona urbana y caserios"],
    ["Los neumáticos gastados", "Problemas de suspensión", "El hidroplaneamiento"],
    ["Todas son correctas", "El atardecer", "El amanecer", "Pavimento resbaladizo"],
    ["Los sistemas de retención", "El sistema de frenos", "El sistema de luces", "El mecanismo de la dirección"],
    ["Verdadero", "Falso"],
    ["Es siempre del peatón", "Es el vehículo si quien cruza lo hace lentamente", "Es el peatón si es acompañado por un niño"],
    ["Todas son correctas", "Frente a una obra en la vía pública", "Frente a una feria", "Frente a un cartel de escuela"],
    ["Ambas son correctas", "Pueden causar la muerte", "Son un evento multicasual"],
    ["En caso de necesidad o para estacionarse", "30 mts", "50 mts", "Ninguna es correcta"],
    ["30 mts", "50 mts", "Ninguna es correcta", "Apretar el pedal suavemente"],
    ["Media cuadra", "Dos cuadras", "10 mts", "25 mts"],
    ["Desviarse hacia la banquina", "Encender las luces", "Frenar", "Rebajar los cambios"],
    ["70-90 km/h", "100-120 km/h", "Ninguna es correcta", "50-60 km/h"],
    ["Verdadero", "Falso"],
    ["45km/h", "75km/h", "60km/h", "110km/h"] ,
    ["45km /h", "60km/h", "30km/h"] ,
    ["En caso de necesidad o para estacionarse", "30 mts", "50mts", "Ninguna es correcta"] ,
    ["30mts", "50mts", "Apretar el pedal suavemente", "Ninguna es correcta"] ,
    ["Media cuadra", "25mts", "10mts", "dos cuadras"] ,
    ["Desviarse hacia la banquina", "Encender las luces", "Rebajar los cambios", "Frenar"] ,
    ["VERDADERO", "FALSO"] ,
    ["VERDADERO", "FALSO"] ,
    ["Neumáticos en buen estado", "Carrocería y chasis", "Cinturón de seguridad", "Airbag"] ,
    ["La calzada", "la acera", "ninguna es correcta", "la banquina"] ,
    ["VERDADERO", "FALSO"] ,
    ["A paso de peatón ", "30km/h", "25km/h", "15 km/h"] ,
    ["FALSO", "VERDADERO"] ,
    ["El vehículo de adelante va doblar a la izquierda ", "nunca", "el vehículo de adelante paso a otros", "el vehículo de adelante va doblar a la derecha"] ,
    ["20 minutos", "50 minutos", "60 minutos", "10 minutos"] ,
    ["VERDAERO", "FALSO"] ,
    ["FALSO", "VERDADERO"] ,
    ["VERDADERO", "FALSO"] ,
    ["Reduce la posibilidad de muerte en un accidente de tránsito", "Los niños no deben utilizarlo", "No es necesario su uso en trayectos cortos", "Cualquier modelo es útil"] ,
    ["Ninguna es correcta", "la luz roja habilita a comenzar el cruce", "en la noche , rige la derecha", "solo los peatones pueden cruzar con la luz roja"] ,
    ["Su uso es importante aun a baja velocidad", "Todas son incorrectas", "Las mujeres embarazadas no deben utilizarlo", "Esta comprobado que en viajes cortos son innecesarios"] ,
    ["Se puede ingresar al mismo para entrar a garaje o girar a la derecha", "Solo puede ingresar al mismo si se necesita cargar o descargar", "Si no hay ómnibus circulando , se puede utilizar libremente"] ,
    ["Todas son correctas", "Falta de orientación en calles desconocidas", "Dificultad de apreciación de la velocidad y distancias de los vehículos "] ,
    ["Todas son correctas", "Sexo y edad", "peso de la persona", "tipo de bebida ingerida"] ,
    ["Luces bajas (cortas)", "Luces altas (largas)", "luces de posición", "ninguna es correcta"] ,
    ["Todas son correctas", "Lo/la compromete legalmente", "Pone en riesgo a todos los usuarios de la via publica"] ,
    ["Todas son correctas ,las ambulancias", "los vehículos del departamento de transito", "patrulleros y bomberos"] ,
    ["debe mantener la calma en todo momento y sujetar el volante firmemente y evitar girarlo para que el vehículo no derrape", "acelera para secar los neumáticos", "frenar ligeramente", "ninguna opción es correcta"] ,
    ["VERDADERO", "FALSO"] ,
    ["90km/h", "entre 60 y 100 km/h", "entre 90 y 120 km/h"] ,
    ["Si, en cualquier caso y durante todo el día mientras estè circulando", "fuera de la ciudad si, dentro de la ciudad no.", "Si pero únicamente en vías con escasos picos de luz."] ,
    ["Todas son correctas", "Por infracción de tránsito", "Porque se constató la presencia de alcohol en sangre por encima de los límites legales"] ,
    ["Detener el vehículo , estacionar y esperar unos minutos a que pueda tener el control de mis emociones", "Continuar la marcha y llegar lo antes posible", "Llamar por teléfono a alguien y explicar mi situacion"] ,
    ["en los canteros centrales", "en la mitad de la cuadra", "ninguna es correcta", "en la acera derecha de las calles de un solo sentido"] ,
    ["FALSA", "VERDADERO"] ,
    ["90 KM/h", "75 km/h", "45km/h", "60 km/h"] ,
    ["FALSO", "VERDADERO"] ,
    ["Acercarse lo más a la derecha posible y prender el señalero", "ninguna es correcta", "mantenerse en el eje de la calzada y prender el señalero", "acercarse a la izquierda lo más posible y prender el señalero"] ,
    ["VERDADERA", "FALSA"] ,
    ["VERDADERO", "FALSO"] ,
    ["VERDADERO", "FALSO"],
    ["FALSO", "VERDADERO"] ,
    ["VERDADERO", "FALSO"] ,
    ["45KM/H", "NINGUNA ES CORRECTA", "60KM/H", "20KM/H"] ,
    ["disminuir la velocidad y estar atento a frenar", "aumentar la velocidad", "no hacer nada"] ,
    ["observe, retírese unos metros del lugar del siniestro y proceda a llamar a los equipos de emergencia por teléfono 911 dando datos de la ubicación del hecho y contando brevemente que se observa", "hacerles caminar", "darles de beber siempre que lo soliciten", "moverlos para quitarles el casco"] ,
    ["la mitad en metros de la velocidad en Km o utilizar la regla de los tres segundos ", "no hay como calcularla", "utilice su teléfono celular", "multiplique por dos la velocidad que circula y tradúzcala en metros"] ,
    ["Adaptar la velocidad de mi vehículo a la visibilidad de la vía", "dejar entre mi vehículo y el que circula delante una distancia mínima de 50mts", "no efectuar ninguna maniobra"] ,
    ["Únicamente en el sentido de circulacion", "A ambos lados de la calzada , en todo caso.", "ambos lados de la calzada , pero solo cuando no se obstaculice la circulación en ambos sentidos"] ,
    ["NO", "Si, pero deberé reintegrarme inmediatamente a mi carril", "Si, no importa que solo este reservado para autobuses si necesito utilizarlo"] ,
    ["VERDADERO", "FALSA"] ,
    ["Falso, reduce en un 70%", "Verdadero"] ,
    ["Verdadero", "Falso"] ,
    ["Todas son correctas", "Fumar mientras conduce", "Uso de sistema GPS", "Usar el celular"] ,
    ["Todas son correctas", "Acercarse al cordón de la izquierda", "Poner en funcionamiento con suficiente antelación y mantener encendido el señalero hasta el final de la maniobra", "El ingreso a la nueva vía , una vez que abandona la intersección debe ser por la senda izquierda del sentido de circulación, para luego situarse en el carril de la derecha"] ,
    ["Pisar a fondo el pedal de freno sin levantar el pie hasta que el vehículo se haya detendio", "Soltar levemente el pedal para disminuir la presión, pero sin dejar de frenar"] ,
    ["Circular a una velocidad superior a la máxima permitida", "Conducir a 90km/h en carretera", "Conducir a 45km/H"] ,
    ["parte de la calzada , separada físicamente del resto de la misma , destinada a la circulación de ómnibus del transporte colectivo de pasajeros y taxis con pasajeros", "todas son correctas", "el carril para la circulación de camionetas escolares", "el carril dedicado exclusivamente a la circulación de camiones de carga"] ,
    ["Todas son correctas", "Advierte al conductor que deberá despejar el cruce", "Advierte la inmediatez de la luz roja", "Advierte al conductor que deberá detenerse a menos que haya comenzado el cruce"] ,
    ["Todas son correctas", "Si detecta una herida que sangra, presione la misma para evitar sangrado", "No ponerle  nada debajo de la cabeza", "No quitar el casco"] ,
    ["Falsa", "Verdadera"] ,
    ["Detención", "Giro a la izquierda", "Giro a la derecha", "Marcha atrás"] ,
    ["VERDADERO", "FALSO"] ,
    ["la dirección del vehículo y la altura de los focos delanteros", "el consumo del combustible", "no se afecta la conducción"] ,
    ["Ninguna de las opciones es correcta", "En repechos y cruces ferroviarios ", "En las proximidades de curva", "En las proximidades de puentes"] ,
    ["no cruzar y dar preferencia de paso a la ambulancia", "Detenerse y comenzar a tocas bocina encendiendo todas las luces del vehículo para hacerse eco de la emergencia y avisar a los demás usuarios", "proseguir la marcha porque Ud. Tiene luz verde al frente y la ambulancia esta en infracción al cruzar con luz rojas"] ,
    ["ninguna es correcta", "tomar un baño frio", "beber cafe", "consumir chocolate"] ,
    ["todas son correctas", "ceder el paso a los peatones", "ceder el paso a quien viene por la derecha", "ceder el paso a quien viene por la izquierda"] ,
    ["todas son correctas", "velocidad excesiva", "desgaste de los neumáticos"] ,
    ["un espacio libre que me permita detener mi vehículo en caso de frenado brusco del que circula delante, y , a su vez , permita al vehículo que me sigue actuar con seguridad.", "50 mts como mínimo", "debo guardar un espacio libre de 1 m y medio que permita detener mi vehículo en caso de frenado brusco  del vehiculo que circula delante sin colisionar con el"] ,
    ["si, se deberá circular como máximo a 45km/h", "no, porque la vía me permite que utilice la velocidad que considere necesaria", "no, porque circulo a una velocidad permitida para las zonas que no tienen carteles indicadores"] ,
    ["no, porque la banquina no es un carril de circulación", "dentro de la ciudad es correcto si la zona es periférica o semi rural. Fuera de la ciudad no.", "si , porque en este caso de estar saturada la via cualquier otra salida es razonable."] ,
    ["todas son correctas", "si es de noche con linterna", "con material reflectivo", "con sentido contrario al tránsito"] ,
    ["NO, en ningún caso", "si, siempre que observe que no se aproxima ningún vehículo que haga uso de las vías del ferrocarril", "si, teniendo la precaución de cruzar antes de que este la barrera completamente baja"] ,
    ["Pierde adherencia y es menos visible al resto del tránsito", "no pasa nada.", "pierde adherencia."] ,
    ["Detención inmediatamente antes de ella y el derecho a seguir queda sujeto a las normas que rigen después de haberse detenido a una señal de PARE.", "Permite el paso de vehículo", "Prohíbe temporalmente el paso de vehículos"] ,
    ["Si, al igual que el resto de los ocupantes del vehículo", "No, si el recorrido es corto.", "No, porque solo se exige utilizar el cinturón en vías interurbanas", "No, si voy a poca velocidad"] ,
    ["realizarla rápidamente , tomando recaudos de seguridad pertinente y haciendo uso de los espejos retrovisores del vehículo", "señalizarla, utilizando las señales acústicas de su vehículo , incluso en ciudad, para advertir de ella a los demás usuarios", "no, recorrer hacia atrás más de quince metros ni invadir el cruce de vías"] ,
];
    
var indice_aleatorio = Math.floor(Math.random()*preguntas.length);
    const cantidad_de_preguntas = 31;
    var my_Array = [];
    var respuestas_bien = [];
    respuestas_bien.length = cantidad_de_preguntas;
    my_Array.length = cantidad_de_preguntas;
    var numeros_repetidos = [];
    var i = 0;
    var j = 0;
    while(i < my_Array.length){
        indice_aleatorio = Math.floor(Math.random()*preguntas.length);
        respuestas_bien[i] = respuestas[indice_aleatorio][0];
        for (j in my_Array){
            // console.log('Entro?');
            if (my_Array[j] === indice_aleatorio){
                numeros_repetidos.push(indice_aleatorio);
                indice_aleatorio = Math.floor(Math.random()*preguntas.length);
            }
            for (j in numeros_repetidos){
                while (indice_aleatorio === numeros_repetidos[j]){
                    indice_aleatorio = Math.floor(Math.random()*preguntas.length) ;
                    j = 0 ;
                }
            }
        }
        my_Array[i] = indice_aleatorio;
        numeros_repetidos[i] = indice_aleatorio;
        i++;
    }
    export var myArray = my_Array;
    export var respuestas_correctas = respuestas_bien;
    // console.log(myArray);